site_name: MineChat Documentation

theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: deep purple

nav:
  - Home: index.md
  - Specification: specification.md
  - Implementation Guides: implementation.md
